version: "3.9"

services:
  environment:
    - NGINX_HOST=hpk.io
    - NGINX_PORT=80

  web-build:
    build:
      context: ./
      dockerfile: etc/Dockerfile
      target: hpk-web-build
    image: hpk-web:build
    container_name: hpk-build
    volumes:
      - ./src:/srv/src
      - ./var:/srv/var
    ports:
      - "8087:80"

  web-dev:
    build:
      context: ./
      dockerfile: etc/Dockerfile
      target: hpk-web-debug
    image: hpk-web:debug
    container_name: hpk-develop
    volumes:
      - ./src:/srv/src
      - ./var:/srv/var
    ports:
      - "8088:80"

    #depends_on:
    #  - db
  #db:
  #  image: postgres
  #  environment:
  #    - POSTGRES_DB=postgres
  #    - POSTGRES_USER=postgres
  #    - POSTGRES_PASSWORD=postgres

  web-stage:
    build:
      context: ./
      dockerfile: etc/Dockerfile
      target: hpk-web-staging
    image: hpk-web:stage
    container_name: hpk-staging
